config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'about' => 'homes#about'

  namespace :admin do
    root 'orders#top'
    patch "orders/order_status" => "orders#order_status_update"
    patch "orders/orders_status" => "orders#orders_status_update"
    resources :customers,      only: [:show, :index, :edit, :update]
    resources :orders,         only: [:show, :update, :index]
    resources :order_details,  only: [:update]
    resources :items
    resources :genres
  end

  scope module: 'public' do
    get 'customers/my_page'         => "customers#show"
    get 'customers/edit'            => "customers#edit"
    patch 'customers'               => "customers#update"
    get 'customers/unsubscribe'     => "customers#unsubscribe"
    patch 'customers/withdraw'      => "customers#withdraw"
    delete 'cart_items'             => "cart_items#destroy_all", as: "cart_items_destroy_all"
    get 'orders/confirm'            => "orders#confirm"
    post 'orders/confirm'           => "orders#confirm"
    get 'orders/thanks'             => "orders#thanks"

    resources :genres,               only: [:show]
    resources :items,                only: [:show, :index]
    resources :cart_items,           only: [:index, :update, :create, :destroy]
    resources :orders,               only: [:new, :show, :index, :create]
    resources :shipping_addresses,   only: [:index, :edit, :create, :update, :destroy]
  end

  # 顧客用
  # URL/customers/sign_in...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL/admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  
  enum status: { buy_now: true, sold_out: false}
  
  def get_item_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default_image.jpeg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height])
  end

  def with_tax_price
    (price*1.1).floor
  end
  
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0}

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      flash[:item_create_error] = "商品の新規登録内容に不備があります"
      redirect_to new_admin_item_path
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :status, :image)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="form-horizontal m-3" role="form">
      <label class="h4 bg-light">商品編集</label>

  　<%= form_with model: @item, url: admin_item_path(params[:id]), method: :patch do |f| %>

  　　<div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :image, '商品画像', class:'control-label' %>
          </div>
          <div class="col-lg-8">
            <%= f.file_field :image, accept: "image/*" %>
          </div>
        </div>
      </div>

  　　<div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :name, '商品名', class:'control-label' %>
          </div>
          <div class="col-lg-8">
            <%= f.text_field :name, autocomplete: "name" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :introduction, '商品説明', class:'control-label' %>
          </div>
          <div class="col-lg-8">
            <%= f.text_area :introduction, autocomplete: "introduction" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :genre_id, 'ジャンル', class:'control-label' %>
          </div>
          <div class="col-lg-8">
            <%= f.select :genre_id, Genre.all.map{ |genre| [genre.genre, genre.id]} %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :price, '税抜価格', class:'control-label' %>
          </div>
          <div class="col-lg-8">
            <%= f.text_field :price, autocomplete: "price" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :status, '販売ステータス', class:'control-label' %>
          </div>
          <div class="col-lg-8">
            <div class="row">
              <%= f.radio_button :status, Item.statuses.key(true) %>
              <%= f.label :status_buy_now, Item.statuses_i18n[:buy_now] %>
            </div>
            <div class="row">
              <%= f.radio_button :status, Item.statuses.key(false) %>
              <%= f.label :status_sold_out, Item.statuses_i18n[:sold_out] %>
            </div>
          </div>
        </div>
      </div>

    　<div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">

          </div>
          <div class="col-lg-8">
            <%= f.submit "変更を保存", class:'btn btn-success' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-4">
      <h2>商品一覧</h2>
    </div>

    <div class="col-4"></div>
    <div class="col-4">
      <h2>
        <%= link_to '＋', new_admin_item_path, class:"btn btn-outline-secondary rounded-circle" %>
      </h2>
    </div>

  </div>

  <div class="row">

    <table class="table" border="1">
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>

      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item.id) %></td>
          <td><%= number_to_currency(item.price, unit: "", strip_insignificant_zeros: true) %></td>
          <td><%= item.genre.genre %></td>
          <td><%= item.status_i18n %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="form-horizontal m-3" role="form">
      <label class="h4 bg-light">商品新規登録</label>
        <div class="error_message">
          <% if flash[:item_create_error] %>
            <p id="item_create_error">
              <%= flash[:item_create_error] %>
            </p>
          <% end %>  

  　<%= form_with model: @item, url: admin_items_path, method: :post do |f| %>

  　　<div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :image, '商品画像', class:'control-label' %>
          </div>
          <div class="col-lg-8">
            <%= f.file_field :image, accept: "image/*" %>
          </div>
        </div>
      </div>

  　　<div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4 ">
            <%= f.label :name, '商品名', class:'control-label' %>
          </div>
          <div class="col-lg-8">
            <%= f.text_field :name, autocomplete: "name", placeholder: "商品名" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :introduction, '商品説明', class:'control-label' %>
          </div>
          <div class="col-lg-8">
            <%= f.text_area :introduction, autocomplete: "introduction", placeholder: "ここに説明文を記述します" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :genre_id, 'ジャンル', class:'control-label' %>
          </div>
          <div class="col-lg-8">
            <%= f.select :genre_id, Genre.all.map{ |genre| [genre.genre, genre.id]} %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :price, '税抜価格', class:'control-label' %>
          </div>
          <div class="col-lg-8">
            <%= f.text_field :price, autocomplete: "price" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :status, '販売ステータス', class:'control-label' %>
          </div>
          <div class="col-lg-8">
            <div class="row">
              <%= f.radio_button :status, Item.statuses.key(true) %>
              <%= f.label :status_buy_now, Item.statuses_i18n[:buy_now] %>
            </div>
            <div class="row">
              <%= f.radio_button :status, Item.statuses.key(false) %>
              <%= f.label :status_sold_out, Item.statuses_i18n[:sold_out] %>
            </div>
          </div>
        </div>
      </div>

    　<div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">

          </div>
          <div class="col-lg-8">
            <%= f.submit "商品追加", class:'btn btn-success' %><br>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row py-4">
    <h5>商品詳細</h5>
  </div>

  <div class="row py-4">
    <div class="col-lg-4">
      <%= image_tag @item.get_item_image(300,200) %>
    </div>

    <div class="col-lg-8">
      <div class="row">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td>商品名</td>
              <td><%= @item.name %></td>
            </tr>
            <tr>
              <td>商品説明</td>
              <td><%= @item.introduction %></td>
            </tr>
            <tr>
              <td>ジャンル</td>
              <td><%= @item.genre.genre %></td>
            </tr>
            <tr>
              <td>税込価格<br>(税抜価格)</td>
              <td>
                <h5><%= (@item.price*1.1).floor.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>) 円</h5>
              </td>
            </tr>
            <tr>
              <td>
                <div class="text-nowrap">販売ステータス</div></td>
              <td>
                <%= @item.status_i18n %>
                <%# if @item.status == false %>
                  <!--p class="text-secondary">販売停止中</p>
                <#% else %>
                  <p class="text-success">販売中</p-->
                <%# end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-lg-5"></div>
      <%= link_to "編集する", edit_admin_item_path(@item), class:"btn btn-success btn-lg" %>
    </div>
  </div>
</div>