config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'about' => 'homes#about'

  namespace :admin do
    root 'orders#top'
    patch "orders/order_status" => "orders#order_status_update"
    patch "orders/orders_status" => "orders#orders_status_update"
    resources :customers,      only: [:show, :index, :edit, :update]
    resources :orders,         only: [:show, :update, :index]
    resources :order_details,  only: [:update]
    resources :items
    resources :genres
  end

  scope module: 'public' do
    get 'customers/my_page'         => "customers#show"
    get 'customers/edit'            => "customers#edit"
    patch 'customers'               => "customers#update"
    get 'customers/unsubscribe'     => "customers#unsubscribe"
    patch 'customers/withdraw'      => "customers#withdraw"
    delete 'cart_items'             => "cart_items#destroy_all", as: "cart_items_destroy_all"
    get 'orders/confirm'            => "orders#confirm"
    post 'orders/confirm'           => "orders#confirm"
    get 'orders/thanks'             => "orders#thanks"

    resources :genres,               only: [:show]
    resources :items,                only: [:show, :index]
    resources :cart_items,           only: [:index, :update, :create, :destroy]
    resources :orders,               only: [:new, :show, :index, :create]
    resources :shipping_addresses,   only: [:index, :edit, :create, :update, :destroy]
  end

  # 顧客用
  # URL/customers/sign_in...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL/admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :shipping_addresses


  validate :last_name, :first_name, :last_name_kana, :first_name_kana,
           :postal_code, :address, :telephone_number, :is_deleted


  ## is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def shipping_address_display
    '〒' + postal_code + ' ' + address
  end

  def full_name_display
    last_name + first_name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(admin_customer_params)
    redirect_to admin_customers_path
  end

  private

  def admin_customer_params
    params.require(:customer).permit(:last_name, :first_name,
                                     :last_name_kana, :first_name_kana,
                                     :postal_code, :address, :telephone_number,
                                     :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row py-5">
    <div class="col">
      <h4>会員情報編集</h4>
    </div>
  </div>

  <div class="row">
    <div class="form-horizontal m-3" role="form">
      <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :id, '会員ID', class:'control-label' %>
          </div>

          <div class="col-lg-4">
          </div>

        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :last_name, '姓', class:'control-label' %>
          </div>
          <div class="col-lg-4">
            <%= f.text_field :last_name, autocomplete: "last_name", placeholder: "長野" %>
          </div>
          <div class="col-lg-2">
            <%= f.label :first_name, '名', class:'control-label' %>
          </div>
          <div class="col-lg-2">
            <%= f.text_field :first_name, autocomplete: "first_name", placeholder: "花子" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :last_name_kana, 'セイ', class:'control-label' %>
          </div>
          <div class="col-lg-4">
            <%= f.text_field :last_name_kana, autocomplete: "last_name_kana", placeholder: "ナガノ" %>
          </div>
          <div class="col-lg-2">
            <%= f.label :first_name_kana, 'メイ', class:'control-label' %>
          </div>
          <div class="col-lg-2">
            <%= f.text_field :first_name_kana, autocomplete: "first_name_kana", placeholder: "ハナコ" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :postal_code, '郵便番号', class:'control-label' %>
          </div>
          <div class="col-lg-4">
            <%= f.text_field :postal_code %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :address, '住所', class:'control-label' %>
          </div>
          <div class="col-lg-4">
            <%= f.text_field :address %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :telephone_number, '電話番号', class:'control-label' %>
          </div>
          <div class="col-lg-4">
            <%= f.text_field :telephone_number %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :email, 'メールアドレス', class:'control-label' %>
          </div>
          <div class="col-lg-4">
            <%= f.email_field :email %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="form-inline">
          <div class="col-lg-4">
            <%= f.label :is_deleted, '会員ステータス', class:'control-label' %>
          </div>
          <div class="col-lg-4">
            <div class="row">
              <span class="admin-is_deleted-radio_button mr-3">
                <%= f.radio_button :is_deleted, true %>
                <%= f.label :is_deleted, '退会', value: true %>
              </span>
              <span class="admin-is_deleted-radio_button">
                <%= f.radio_button :is_deleted, false %>
                <%= f.label :is_deleted, '有効', value: false %>
              </span>
            </div>
          </div>
        </div>
      </div>

      <div class="row py-4">
        <div class="col-4">
          <%= f.submit '変更を保存', class: "btn btn-success" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-4">
      <h2>会員一覧</h2>
    </div>
  </div>

  <div class="row py-4">
    <table class="table" border="1">
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>

      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td>
          <td><% if customer.is_deleted == true %>
              <p class="text-secondary">退会済</p>
            <% else %>
              <p class="text-success">有効</p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row py-4">
    <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細
  </div>

  <div class="row py-3">
    <div class="col-5">
      <table class="table" border="1">
        <tr>
          <th>氏名</th>
          <td><%= @customer.last_name %><%= @customer.first_name %></td>
        </tr>
        <tr>
          <th>カナ</th>
          <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td><% if @customer.is_deleted == true %>
              <p class="text-secondary">退会済</p>
            <% else %>
              <p class="text-success">有効</p>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row py-4">
    <div class="col-4">
      <%= link_to edit_admin_customer_path do %>
        <button class="btn btn-success">編集する</button>
      <% end %>
    </div>

    <div class="col-4"></div>

    <div class="col-4">

    </div>
  </div>
</div>