config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'about' => 'homes#about'

  namespace :admin do
    root 'orders#top'
    patch "orders/order_status" => "orders#order_status_update"
    patch "orders/orders_status" => "orders#orders_status_update"
    resources :customers,      only: [:show, :index, :edit, :update]
    resources :orders,         only: [:show, :update, :index]
    resources :order_details,  only: [:update]
    resources :items
    resources :genres
  end

  scope module: 'public' do
    get 'customers/my_page'         => "customers#show"
    get 'customers/edit'            => "customers#edit"
    patch 'customers'               => "customers#update"
    get 'customers/unsubscribe'     => "customers#unsubscribe"
    patch 'customers/withdraw'      => "customers#withdraw"
    delete 'cart_items'             => "cart_items#destroy_all", as: "cart_items_destroy_all"
    get 'orders/confirm'            => "orders#confirm"
    post 'orders/confirm'           => "orders#confirm"
    get 'orders/thanks'             => "orders#thanks"

    resources :genres,               only: [:show]
    resources :items,                only: [:show, :index]
    resources :cart_items,           only: [:index, :update, :create, :destroy]
    resources :orders,               only: [:new, :show, :index, :create]
    resources :shipping_addresses,   only: [:index, :edit, :create, :update, :destroy]
  end

  # 顧客用
  # URL/customers/sign_in...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL/admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :genre, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!,only: [:create,:edit,:update,:index]

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      flash[:genre_create_error] = "ジャンル名を入力してください"
      @genres = Genre.all
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      flash[:genre_edit_error] = "ジャンル名を入力してください"
      @genre = Genre.find(params[:id])
      redirect_to edit_admin_genre_path(@genre)
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:genre)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <label class="h4 bg-light">ジャンル編集</label>

  <div class="row">
    <div class="col-lg-10">
      <% if flash[:genre_edit_error] %>
        <p class="text-danger" id="genre_edit_error">
          <%= flash[:genre_edit_error] %>
        </p>
      <% end %>      
      <div class="form mt-5 mb-5">
        <%= form_with model: @genre, url: admin_genre_path do |f| %>
          <%= f.label :ジャンル, class:"mr-3"%>
          <%= f.text_field :genre %>
          <%= f.submit "変更を保存", class:"btn btn-success ml-3" %>
        <% end %>      
      </div>
    </div>
  </div>
</div>
    
    </table>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <label class="h4 bg-light mb-5">ジャンル追加・一覧画面</label>
  <div class="row">
    <div class="col-lg-10">
      <% if flash[:genre_create_error] %>
        <p class="text-danger" id="genre_create_error">
          <%= flash[:genre_create_error] %>
        </p>
      <% end %>
      <div class="form mx-5">
        <%= form_with model: @genre, url: admin_genres_path do |f| %>
          <%= f.label :ジャンル名, class:"mr-3" %>
          <%= f.text_field :genre %>
          <%= f.submit "新規登録", class:"btn btn-success ml-3" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <table class="table shadow-sm mt-5">
        <thead class="bg-light">
          <tr>
            <th>ジャンル</th>
            <th colspan="1"></th>
          </tr>
        </thead>
        <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.genre %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre), class:"btn btn-success" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>