config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'about' => 'homes#about'

  namespace :admin do
    root 'orders#top'
    patch "orders/order_status" => "orders#order_status_update"
    patch "orders/orders_status" => "orders#orders_status_update"
    resources :customers,      only: [:show, :index, :edit, :update]
    resources :orders,         only: [:show, :update, :index]
    resources :order_details,  only: [:update]
    resources :items
    resources :genres
  end

  scope module: 'public' do
    get 'customers/my_page'         => "customers#show"
    get 'customers/edit'            => "customers#edit"
    patch 'customers'               => "customers#update"
    get 'customers/unsubscribe'     => "customers#unsubscribe"
    patch 'customers/withdraw'      => "customers#withdraw"
    delete 'cart_items'             => "cart_items#destroy_all", as: "cart_items_destroy_all"
    get 'orders/confirm'            => "orders#confirm"
    post 'orders/confirm'           => "orders#confirm"
    get 'orders/thanks'             => "orders#thanks"

    resources :genres,               only: [:show]
    resources :items,                only: [:show, :index]
    resources :cart_items,           only: [:index, :update, :create, :destroy]
    resources :orders,               only: [:new, :show, :index, :create]
    resources :shipping_addresses,   only: [:index, :edit, :create, :update, :destroy]
  end

  # 顧客用
  # URL/customers/sign_in...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL/admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  validates :amount, presence: true
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :shipping_addresses


  validate :last_name, :first_name, :last_name_kana, :first_name_kana,
           :postal_code, :address, :telephone_number, :is_deleted


  ## is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def shipping_address_display
    '〒' + postal_code + ' ' + address
  end

  def full_name_display
    last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :genre, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  
  enum status: { buy_now: true, sold_out: false}
  
  def get_item_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default_image.jpeg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height])
  end

  def with_tax_price
    (price*1.1).floor
  end
  
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0}

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
    
  enum payment_method: { credit_card: 0, transfer: 1}
  enum order_status: { wait: 0, payment_check: 1, making: 2, ready_to_ship: 3, goal: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: {
    non_production: 0,
    awaiting_production: 1,
    in_production: 2,
    production_complete: 3
  }
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer

  validates :postal_code, presence: true
  validates :address,     presence: true
  validates :name,        presence: true

  def shipping_address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      flash[:item_create_error] = "商品の新規登録内容に不備があります"
      redirect_to new_admin_item_path
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :status, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_up_path_for(resource)
    if resource == :admin
      root_path
    else
      customers_my_page_path
    end
  end

  def after_sign_in_path_for(resource)
    if resource == :admin
      root_path
    else
      customers_my_page_path
    end
  end



  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name,
                                                       :last_name_kana, :first_name_kana,
                                                       :postal_code, :address, :telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @genres = Genre.all
    @items = Item.order('id DESC').limit(4)
  end
  
  def about
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>nagano_cake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="row col-12  justify-content-between align-items-center">
        <div class="container">
          <div class="col-4 mt-4">
            <h1 class="sample">
              <%= link_to 'Nagano-cake', root_path, data: {"turbolinks" => false}, style: "font-family: HiraMinPro-W6; color: #000000;" %>
            </h1>

            <% if customer_signed_in? %>
              <p>ログイン中</p>
            <% end %>
          </div>

          <div class="col-8">
            <ul class="list-group list-group-horizontal">
              <% if customer_signed_in? %>

                <li class="nav-item my-3 mr-9 ">
                  <%= "ようこそ#{current_customer.last_name}さん！" %>
                </li>

                <li class="nav-item btn btn-outline-secondary mr-2">
                  <%= link_to "マイページ", customers_my_page_path, class: 'nav-link text-dark' %>
                  </li>
                <li class="nav-item btn btn-outline-secondary mr-2">
                  <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item btn btn-outline-secondary mr-2">
                  <%= link_to "カート", cart_items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item btn btn-outline-secondary mr-2">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
                </li>

              <% elsif admin_signed_in? %>
                <li class="nav-item btn btn-outline-secondary px-1 mx-2">
                  <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item btn btn-outline-secondary px-1 mx-2">
                  <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item btn btn-outline-secondary px-1 mx-2">
                  <%= link_to "注文履歴一覧", admin_orders_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item btn btn-outline-secondary px-1 mx-2">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item btn btn-outline-secondary px-1 mx-2">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
                </li>

              <% else %>
                <li class="nav-item btn btn-outline-secondary mx-4">
                  <%= link_to "About", about_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item btn btn-outline-secondary mx-4">
                  <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item btn btn-outline-secondary mx-4">
                  <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item btn btn-outline-secondary mx-4">
                  <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
                </li>

              <% end %>
            </ul>
          </div>

          <div class="col-3">
          </div>

          <div class="col-3 mt-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search">
              <button class="btn btn-outline-success" type="button" id="button-addon2">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>

        </div>
      </div>
    </header>

    <div class="shadow-sm mt-3 pb-3">
      <%= yield %>
    </div>

    <footer>
      <div class="container">
        <div class="small text-center text-dark" style="margin: 40px 0;">
          Copyright © Infratop Inc. All Rights Reserved.
        </div>
      </div>
    </footer>
  </body>

</html>